### ISSUE TITLE
可否在ReadMe之类的文件中提供API文档供他人开发

### ISSUE THREAD

**Issue by TuanZiGit** [HelloWRC/ClassIsland.ManagementServer#5]
如题，可否提供详细接口文档，以便实现兼容ClassIsland集控的其他课表/兼容ClassIsland的第三方集控服务端

**Comment by jiangyin14** [comment]
感谢您对本项目的关注。

后续补充在
https://docs.classisland.tech/

**Comment by HelloWRC** [comment]
目前集控服务器还处于早期开发阶段，像是api之类的很多内容还没有定型。目前计划在把前端控制台完成后（大概是0.2）发布集控服务器的api文档。
